//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 05:15:04 PM IST 
//


package com.avn.ccl.bean.serviceclient.fullprofile;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="response" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BUSINESS_SECTOR_ID_PK" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="SUB_SECTOR_ID_FK" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="BUSINESS_ID_FK" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="SUB_SECTOR_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RECORD_STATUS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response"
})
@XmlRootElement(name = "businessesSubSectors", namespace = "http://cclk.lk/schemas/entity/microfinance/v1")
public class BusinessesSubSectors {

    @XmlElement(namespace = "http://cclk.lk/schemas/entity/microfinance/v1")
    protected List<BusinessesSubSectors.Response> response;

    /**
     * Gets the value of the response property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the response property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BusinessesSubSectors.Response }
     * 
     * 
     */
    public List<BusinessesSubSectors.Response> getResponse() {
        if (response == null) {
            response = new ArrayList<BusinessesSubSectors.Response>();
        }
        return this.response;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BUSINESS_SECTOR_ID_PK" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="SUB_SECTOR_ID_FK" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="BUSINESS_ID_FK" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="SUB_SECTOR_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RECORD_STATUS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "businesssectoridpk",
        "subsectoridfk",
        "businessidfk",
        "subsectorname",
        "recordstatus",
        "version",
        "type"
    })
    public static class Response {

        @XmlElement(name = "BUSINESS_SECTOR_ID_PK", namespace = "http://cclk.lk/schemas/entity/microfinance/v1")
        protected short businesssectoridpk;
        @XmlElement(name = "SUB_SECTOR_ID_FK", namespace = "http://cclk.lk/schemas/entity/microfinance/v1")
        protected short subsectoridfk;
        @XmlElement(name = "BUSINESS_ID_FK", namespace = "http://cclk.lk/schemas/entity/microfinance/v1")
        protected int businessidfk;
        @XmlElement(name = "SUB_SECTOR_NAME", namespace = "http://cclk.lk/schemas/entity/microfinance/v1", required = true)
        protected String subsectorname;
        @XmlElement(name = "RECORD_STATUS", namespace = "http://cclk.lk/schemas/entity/microfinance/v1")
        protected byte recordstatus;
        @XmlElement(name = "VERSION", namespace = "http://cclk.lk/schemas/entity/microfinance/v1")
        protected byte version;
        @XmlElement(name = "TYPE", namespace = "http://cclk.lk/schemas/entity/microfinance/v1", required = true)
        protected String type;

        /**
         * Gets the value of the businesssectoridpk property.
         * 
         */
        public short getBUSINESSSECTORIDPK() {
            return businesssectoridpk;
        }

        /**
         * Sets the value of the businesssectoridpk property.
         * 
         */
        public void setBUSINESSSECTORIDPK(short value) {
            this.businesssectoridpk = value;
        }

        /**
         * Gets the value of the subsectoridfk property.
         * 
         */
        public short getSUBSECTORIDFK() {
            return subsectoridfk;
        }

        /**
         * Sets the value of the subsectoridfk property.
         * 
         */
        public void setSUBSECTORIDFK(short value) {
            this.subsectoridfk = value;
        }

        /**
         * Gets the value of the businessidfk property.
         * 
         */
        public int getBUSINESSIDFK() {
            return businessidfk;
        }

        /**
         * Sets the value of the businessidfk property.
         * 
         */
        public void setBUSINESSIDFK(int value) {
            this.businessidfk = value;
        }

        /**
         * Gets the value of the subsectorname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSUBSECTORNAME() {
            return subsectorname;
        }

        /**
         * Sets the value of the subsectorname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSUBSECTORNAME(String value) {
            this.subsectorname = value;
        }

        /**
         * Gets the value of the recordstatus property.
         * 
         */
        public byte getRECORDSTATUS() {
            return recordstatus;
        }

        /**
         * Sets the value of the recordstatus property.
         * 
         */
        public void setRECORDSTATUS(byte value) {
            this.recordstatus = value;
        }

        /**
         * Gets the value of the version property.
         * 
         */
        public byte getVERSION() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         */
        public void setVERSION(byte value) {
            this.version = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTYPE() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTYPE(String value) {
            this.type = value;
        }

    }

}
