//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 05:15:04 PM IST 
//


package com.avn.ccl.bean.serviceclient.fullprofile;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.avn.ccl.bean.serviceclient.fullprofile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CustomerDataResponseCustomerBusinessDataResponseBUSINESSPLACE_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "BUSINESS_PLACE");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseNOOFEMPLOYEES_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "NO_OF_EMPLOYEES");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseNAME_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "NAME");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseOTHEREMPLOYEMENT_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "OTHER_EMPLOYEMENT");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseOWNERSHIPTYPE_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "OWNERSHIP_TYPE");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseEMPLOYERIDFK_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "EMPLOYER_ID_FK");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseSECTORIDFK_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "SECTOR_ID_FK");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseDURATIONFREQUENCE_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "DURATION_FREQUENCE");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseBUSINESSIDPK_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "BUSINESS_ID_PK");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseHANDLEBY_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "HANDLE_BY");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseMARKETREPUTATION_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "MARKET_REPUTATION");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseBRN_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "BRN");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseRECORDSTATUS_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "RECORD_STATUS");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseDESIGNATIONIDFK_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "DESIGNATION_ID_FK");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseSECTORNAME_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "SECTOR_NAME");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponsePROFFESIONIDFK_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "PROFFESION_ID_FK");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseWEBSITE_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "WEB_SITE");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseSHAREPERCENTAGE_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "SHARE_PERCENTAGE");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseEMPLOYEELEVEL_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "EMPLOYEE_LEVEL");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseEMAIL_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "EMAIL");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseTYPE_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "TYPE");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseDURATION_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "DURATION");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseCURRENTSTATUS_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "CURRENT_STATUS");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseSTAKEHOLDERREFERENCENO_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "STAKEHOLDER_REFERENCE_NO");
    private final static QName _CustomerDataResponseCustomerBusinessDataResponseVERSION_QNAME = new QName("http://cclk.lk/schemas/entity/savings/v1", "VERSION");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.avn.ccl.bean.serviceclient.fullprofile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerData }
     * 
     */
    public CustomerData createCustomerData() {
        return new CustomerData();
    }

    /**
     * Create an instance of {@link BusinessesSubSectors }
     * 
     */
    public BusinessesSubSectors createBusinessesSubSectors() {
        return new BusinessesSubSectors();
    }

    /**
     * Create an instance of {@link StakeholderFD }
     * 
     */
    public StakeholderFD createStakeholderFD() {
        return new StakeholderFD();
    }

    /**
     * Create an instance of {@link StakeholderSavings }
     * 
     */
    public StakeholderSavings createStakeholderSavings() {
        return new StakeholderSavings();
    }

    /**
     * Create an instance of {@link CustomerData.Response }
     * 
     */
    public CustomerData.Response createCustomerDataResponse() {
        return new CustomerData.Response();
    }

    /**
     * Create an instance of {@link CustomerData.Response.GetCustomerLoan }
     * 
     */
    public CustomerData.Response.GetCustomerLoan createCustomerDataResponseGetCustomerLoan() {
        return new CustomerData.Response.GetCustomerLoan();
    }

    /**
     * Create an instance of {@link CustomerData.Response.AttachmentDetails }
     * 
     */
    public CustomerData.Response.AttachmentDetails createCustomerDataResponseAttachmentDetails() {
        return new CustomerData.Response.AttachmentDetails();
    }

    /**
     * Create an instance of {@link CustomerData.Response.ContactPersonDetails }
     * 
     */
    public CustomerData.Response.ContactPersonDetails createCustomerDataResponseContactPersonDetails() {
        return new CustomerData.Response.ContactPersonDetails();
    }

    /**
     * Create an instance of {@link CustomerData.Response.EducationDetails }
     * 
     */
    public CustomerData.Response.EducationDetails createCustomerDataResponseEducationDetails() {
        return new CustomerData.Response.EducationDetails();
    }

    /**
     * Create an instance of {@link CustomerData.Response.CustomerBusinessData }
     * 
     */
    public CustomerData.Response.CustomerBusinessData createCustomerDataResponseCustomerBusinessData() {
        return new CustomerData.Response.CustomerBusinessData();
    }

    /**
     * Create an instance of {@link CustomerData.Response.CustomerAddressData }
     * 
     */
    public CustomerData.Response.CustomerAddressData createCustomerDataResponseCustomerAddressData() {
        return new CustomerData.Response.CustomerAddressData();
    }

    /**
     * Create an instance of {@link BusinessesSubSectors.Response }
     * 
     */
    public BusinessesSubSectors.Response createBusinessesSubSectorsResponse() {
        return new BusinessesSubSectors.Response();
    }

    /**
     * Create an instance of {@link StakeholderFD.Response }
     * 
     */
    public StakeholderFD.Response createStakeholderFDResponse() {
        return new StakeholderFD.Response();
    }

    /**
     * Create an instance of {@link StakeholderSavings.Response }
     * 
     */
    public StakeholderSavings.Response createStakeholderSavingsResponse() {
        return new StakeholderSavings.Response();
    }

    /**
     * Create an instance of {@link CustomerData.Response.GetCustomerLoan.Response }
     * 
     */
    public CustomerData.Response.GetCustomerLoan.LoanResponse createCustomerDataResponseGetCustomerLoanResponse() {
        return new CustomerData.Response.GetCustomerLoan.LoanResponse();
    }

    /**
     * Create an instance of {@link CustomerData.Response.AttachmentDetails.Response }
     * 
     */
    public CustomerData.Response.AttachmentDetails.AttachmentResponse createCustomerDataResponseAttachmentDetailsResponse() {
        return new CustomerData.Response.AttachmentDetails.AttachmentResponse();
    }

    /**
     * Create an instance of {@link CustomerData.Response.ContactPersonDetails.Response }
     * 
     */
    public CustomerData.Response.ContactPersonDetails.ContactPersonResponse createCustomerDataResponseContactPersonDetailsResponse() {
        return new CustomerData.Response.ContactPersonDetails.ContactPersonResponse();
    }

    /**
     * Create an instance of {@link CustomerData.Response.EducationDetails.Response }
     * 
     */
    public CustomerData.Response.EducationDetails.EducationResponse createCustomerDataResponseEducationDetailsResponse() {
        return new CustomerData.Response.EducationDetails.EducationResponse();
    }

    /**
     * Create an instance of {@link CustomerData.Response.CustomerBusinessData.Response }
     * 
     */
    public CustomerData.Response.CustomerBusinessData.BusinessResponse createCustomerDataResponseCustomerBusinessDataResponse() {
        return new CustomerData.Response.CustomerBusinessData.BusinessResponse();
    }

    /**
     * Create an instance of {@link CustomerData.Response.CustomerAddressData.Response }
     * 
     */
    public CustomerData.Response.CustomerAddressData.AddressResponse createCustomerDataResponseCustomerAddressDataResponse() {
        return new CustomerData.Response.CustomerAddressData.AddressResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "BUSINESS_PLACE", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseBUSINESSPLACE(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseBUSINESSPLACE_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "NO_OF_EMPLOYEES", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<Integer> createCustomerDataResponseCustomerBusinessDataResponseNOOFEMPLOYEES(Integer value) {
        return new JAXBElement<Integer>(_CustomerDataResponseCustomerBusinessDataResponseNOOFEMPLOYEES_QNAME, Integer.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "NAME", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseNAME(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseNAME_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "OTHER_EMPLOYEMENT", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseOTHEREMPLOYEMENT(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseOTHEREMPLOYEMENT_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "OWNERSHIP_TYPE", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseOWNERSHIPTYPE(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseOWNERSHIPTYPE_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "EMPLOYER_ID_FK", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseEMPLOYERIDFK(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseEMPLOYERIDFK_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "SECTOR_ID_FK", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<BigInteger> createCustomerDataResponseCustomerBusinessDataResponseSECTORIDFK(BigInteger value) {
        return new JAXBElement<BigInteger>(_CustomerDataResponseCustomerBusinessDataResponseSECTORIDFK_QNAME, BigInteger.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "DURATION_FREQUENCE", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseDURATIONFREQUENCE(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseDURATIONFREQUENCE_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "BUSINESS_ID_PK", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<BigInteger> createCustomerDataResponseCustomerBusinessDataResponseBUSINESSIDPK(BigInteger value) {
        return new JAXBElement<BigInteger>(_CustomerDataResponseCustomerBusinessDataResponseBUSINESSIDPK_QNAME, BigInteger.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "HANDLE_BY", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseHANDLEBY(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseHANDLEBY_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "MARKET_REPUTATION", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseMARKETREPUTATION(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseMARKETREPUTATION_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "BRN", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseBRN(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseBRN_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "RECORD_STATUS", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<Byte> createCustomerDataResponseCustomerBusinessDataResponseRECORDSTATUS(Byte value) {
        return new JAXBElement<Byte>(_CustomerDataResponseCustomerBusinessDataResponseRECORDSTATUS_QNAME, Byte.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "DESIGNATION_ID_FK", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<BigInteger> createCustomerDataResponseCustomerBusinessDataResponseDESIGNATIONIDFK(BigInteger value) {
        return new JAXBElement<BigInteger>(_CustomerDataResponseCustomerBusinessDataResponseDESIGNATIONIDFK_QNAME, BigInteger.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "SECTOR_NAME", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseSECTORNAME(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseSECTORNAME_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "PROFFESION_ID_FK", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<BigInteger> createCustomerDataResponseCustomerBusinessDataResponsePROFFESIONIDFK(BigInteger value) {
        return new JAXBElement<BigInteger>(_CustomerDataResponseCustomerBusinessDataResponsePROFFESIONIDFK_QNAME, BigInteger.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "WEB_SITE", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseWEBSITE(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseWEBSITE_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "SHARE_PERCENTAGE", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<Byte> createCustomerDataResponseCustomerBusinessDataResponseSHAREPERCENTAGE(Byte value) {
        return new JAXBElement<Byte>(_CustomerDataResponseCustomerBusinessDataResponseSHAREPERCENTAGE_QNAME, Byte.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "EMPLOYEE_LEVEL", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<Byte> createCustomerDataResponseCustomerBusinessDataResponseEMPLOYEELEVEL(Byte value) {
        return new JAXBElement<Byte>(_CustomerDataResponseCustomerBusinessDataResponseEMPLOYEELEVEL_QNAME, Byte.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "EMAIL", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseEMAIL(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseEMAIL_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "TYPE", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseTYPE(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseTYPE_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "DURATION", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<Byte> createCustomerDataResponseCustomerBusinessDataResponseDURATION(Byte value) {
        return new JAXBElement<Byte>(_CustomerDataResponseCustomerBusinessDataResponseDURATION_QNAME, Byte.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "CURRENT_STATUS", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseCURRENTSTATUS(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseCURRENTSTATUS_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "STAKEHOLDER_REFERENCE_NO", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<String> createCustomerDataResponseCustomerBusinessDataResponseSTAKEHOLDERREFERENCENO(String value) {
        return new JAXBElement<String>(_CustomerDataResponseCustomerBusinessDataResponseSTAKEHOLDERREFERENCENO_QNAME, String.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cclk.lk/schemas/entity/savings/v1", name = "VERSION", scope = CustomerData.Response.CustomerBusinessData.BusinessResponse.class)
    public JAXBElement<Byte> createCustomerDataResponseCustomerBusinessDataResponseVERSION(Byte value) {
        return new JAXBElement<Byte>(_CustomerDataResponseCustomerBusinessDataResponseVERSION_QNAME, Byte.class, CustomerData.Response.CustomerBusinessData.BusinessResponse.class, value);
    }

}
