//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.19 at 02:46:38 PM IST 
//


package com.avn.ccl.bean.serviceclient.fullprofile;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="response" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fd_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="depamt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="fd_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="fd_prd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fd_inrate" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="center" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fd_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fd_monint" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="fd_next" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response"
})
@XmlRootElement(name = "stakeholderFD")
public class StakeholderFD {

    protected List<StakeholderFD.Response> response;

    /**
     * Gets the value of the response property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the response property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StakeholderFD.Response }
     * 
     * 
     */
    public List<StakeholderFD.Response> getResponse() {
        if (response == null) {
            response = new ArrayList<StakeholderFD.Response>();
        }
        return this.response;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fd_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="depamt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="fd_date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="fd_prd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fd_inrate" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="center" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fd_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fd_monint" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="fd_next" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fdNo",
        "depamt",
        "fdDate",
        "fdPrd",
        "fdInrate",
        "center",
        "fdType",
        "fdMonint",
        "fdNext"
    })
    public static class Response {

        @XmlElement(name = "fd_no", required = true)
        protected String fdNo;
        @XmlElement(required = true)
        protected BigDecimal depamt;
        @XmlElement(name = "fd_date", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fdDate;
        @XmlElement(name = "fd_prd", required = true)
        protected String fdPrd;
        @XmlElement(name = "fd_inrate")
        protected float fdInrate;
        @XmlElement(required = true)
        protected String center;
        @XmlElement(name = "fd_type", required = true)
        protected String fdType;
        @XmlElement(name = "fd_monint", required = true)
        protected BigDecimal fdMonint;
        @XmlElement(name = "fd_next", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fdNext;

        /**
         * Gets the value of the fdNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFdNo() {
            return fdNo;
        }

        /**
         * Sets the value of the fdNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFdNo(String value) {
            this.fdNo = value;
        }

        /**
         * Gets the value of the depamt property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDepamt() {
            return depamt;
        }

        /**
         * Sets the value of the depamt property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDepamt(BigDecimal value) {
            this.depamt = value;
        }

        /**
         * Gets the value of the fdDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFdDate() {
            return fdDate;
        }

        /**
         * Sets the value of the fdDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFdDate(XMLGregorianCalendar value) {
            this.fdDate = value;
        }

        /**
         * Gets the value of the fdPrd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFdPrd() {
            return fdPrd;
        }

        /**
         * Sets the value of the fdPrd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFdPrd(String value) {
            this.fdPrd = value;
        }

        /**
         * Gets the value of the fdInrate property.
         * 
         */
        public float getFdInrate() {
            return fdInrate;
        }

        /**
         * Sets the value of the fdInrate property.
         * 
         */
        public void setFdInrate(float value) {
            this.fdInrate = value;
        }

        /**
         * Gets the value of the center property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCenter() {
            return center;
        }

        /**
         * Sets the value of the center property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCenter(String value) {
            this.center = value;
        }

        /**
         * Gets the value of the fdType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFdType() {
            return fdType;
        }

        /**
         * Sets the value of the fdType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFdType(String value) {
            this.fdType = value;
        }

        /**
         * Gets the value of the fdMonint property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getFdMonint() {
            return fdMonint;
        }

        /**
         * Sets the value of the fdMonint property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setFdMonint(BigDecimal value) {
            this.fdMonint = value;
        }

        /**
         * Gets the value of the fdNext property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFdNext() {
            return fdNext;
        }

        /**
         * Sets the value of the fdNext property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFdNext(XMLGregorianCalendar value) {
            this.fdNext = value;
        }

    }

}
