//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 05:15:04 PM IST 
//


package com.avn.ccl.bean.serviceclient.fullprofile;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="response" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PRODUCT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PERFORM_LOCATION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SERVICING_LOCATION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SERVICING_OFFICER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ACCOUNT_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ACCOUNT_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CURRENT_BALANCE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="HOLD_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="AVAILABLE_BALANCE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="ACCOUNT_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response"
})
@XmlRootElement(name = "stakeholderSavings")
public class StakeholderSavings {

    protected List<StakeholderSavings.Response> response;

    /**
     * Gets the value of the response property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the response property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StakeholderSavings.Response }
     * 
     * 
     */
    public List<StakeholderSavings.Response> getResponse() {
        if (response == null) {
            response = new ArrayList<StakeholderSavings.Response>();
        }
        return this.response;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PRODUCT_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PERFORM_LOCATION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SERVICING_LOCATION_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SERVICING_OFFICER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ACCOUNT_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ACCOUNT_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CURRENT_BALANCE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="HOLD_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="AVAILABLE_BALANCE" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="ACCOUNT_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productcode",
        "performlocationcode",
        "servicinglocationcode",
        "servicingofficer",
        "accountnumber",
        "accounttype",
        "currentbalance",
        "holdamount",
        "availablebalance",
        "accountstatus"
    })
    public static class Response {

        @XmlElement(name = "PRODUCT_CODE", required = true)
        protected String productcode;
        @XmlElement(name = "PERFORM_LOCATION_CODE", required = true)
        protected String performlocationcode;
        @XmlElement(name = "SERVICING_LOCATION_CODE", required = true)
        protected String servicinglocationcode;
        @XmlElement(name = "SERVICING_OFFICER", required = true, nillable = true)
        protected String servicingofficer;
        @XmlElement(name = "ACCOUNT_NUMBER", required = true)
        protected String accountnumber;
        @XmlElement(name = "ACCOUNT_TYPE", required = true)
        protected String accounttype;
        @XmlElement(name = "CURRENT_BALANCE", required = true)
        protected BigDecimal currentbalance;
        @XmlElement(name = "HOLD_AMOUNT", required = true)
        protected BigDecimal holdamount;
        @XmlElement(name = "AVAILABLE_BALANCE", required = true)
        protected BigDecimal availablebalance;
        @XmlElement(name = "ACCOUNT_STATUS", required = true)
        protected String accountstatus;

        /**
         * Gets the value of the productcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPRODUCTCODE() {
            return productcode;
        }

        /**
         * Sets the value of the productcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPRODUCTCODE(String value) {
            this.productcode = value;
        }

        /**
         * Gets the value of the performlocationcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPERFORMLOCATIONCODE() {
            return performlocationcode;
        }

        /**
         * Sets the value of the performlocationcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPERFORMLOCATIONCODE(String value) {
            this.performlocationcode = value;
        }

        /**
         * Gets the value of the servicinglocationcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSERVICINGLOCATIONCODE() {
            return servicinglocationcode;
        }

        /**
         * Sets the value of the servicinglocationcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSERVICINGLOCATIONCODE(String value) {
            this.servicinglocationcode = value;
        }

        /**
         * Gets the value of the servicingofficer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSERVICINGOFFICER() {
            return servicingofficer;
        }

        /**
         * Sets the value of the servicingofficer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSERVICINGOFFICER(String value) {
            this.servicingofficer = value;
        }

        /**
         * Gets the value of the accountnumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACCOUNTNUMBER() {
            return accountnumber;
        }

        /**
         * Sets the value of the accountnumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACCOUNTNUMBER(String value) {
            this.accountnumber = value;
        }

        /**
         * Gets the value of the accounttype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACCOUNTTYPE() {
            return accounttype;
        }

        /**
         * Sets the value of the accounttype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACCOUNTTYPE(String value) {
            this.accounttype = value;
        }

        /**
         * Gets the value of the currentbalance property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCURRENTBALANCE() {
            return currentbalance;
        }

        /**
         * Sets the value of the currentbalance property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCURRENTBALANCE(BigDecimal value) {
            this.currentbalance = value;
        }

        /**
         * Gets the value of the holdamount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getHOLDAMOUNT() {
            return holdamount;
        }

        /**
         * Sets the value of the holdamount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setHOLDAMOUNT(BigDecimal value) {
            this.holdamount = value;
        }

        /**
         * Gets the value of the availablebalance property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAVAILABLEBALANCE() {
            return availablebalance;
        }

        /**
         * Sets the value of the availablebalance property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAVAILABLEBALANCE(BigDecimal value) {
            this.availablebalance = value;
        }

        /**
         * Gets the value of the accountstatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACCOUNTSTATUS() {
            return accountstatus;
        }

        /**
         * Sets the value of the accountstatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACCOUNTSTATUS(String value) {
            this.accountstatus = value;
        }

    }

}
