//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.03 at 03:22:46 PM IST 
//


package com.avn.ccl.bean.serviceclient.userdetail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="response">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NIC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TITLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="INITIALS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LASTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FIRSTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DATE_OF_BIRTH" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="GENDER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MARITAL_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EPF_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DEPARTMENT_ID_FK" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="DESIGNATION_ID_FK" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="LOCATION_ID_FK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="GRADE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OFFICE_MOBILE_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response"
})
@XmlRootElement(name = "results")
public class UserDetail {

    @XmlElement(required = true)
    protected UserDetail.Response response;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Results.Response }
     *     
     */
    public UserDetail.Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Results.Response }
     *     
     */
    public void setResponse(UserDetail.Response value) {
        this.response = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NIC" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TITLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="INITIALS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LASTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FIRSTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DATE_OF_BIRTH" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="GENDER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MARITAL_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EPF_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="DEPARTMENT_ID_FK" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="DESIGNATION_ID_FK" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="LOCATION_ID_FK" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="GRADE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OFFICE_MOBILE_NO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nic",
        "title",
        "initials",
        "lastname",
        "firstname",
        "dateofbirth",
        "gender",
        "maritalstatus",
        "epfno",
        "departmentidfk",
        "designationidfk",
        "locationidfk",
        "grade",
        "officemobileno"
    })
    public static class Response {

        @XmlElement(name = "NIC", required = true)
        protected String nic;
        @XmlElement(name = "TITLE", required = true)
        protected String title;
        @XmlElement(name = "INITIALS", required = true)
        protected String initials;
        @XmlElement(name = "LASTNAME", required = true)
        protected String lastname;
        @XmlElement(name = "FIRSTNAME", required = true)
        protected String firstname;
        @XmlElement(name = "DATE_OF_BIRTH", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar dateofbirth;
        @XmlElement(name = "GENDER", required = true)
        protected String gender;
        @XmlElement(name = "MARITAL_STATUS", required = true)
        protected String maritalstatus;
        @XmlElement(name = "EPF_NO", required = true)
        protected String epfno;
        @XmlElement(name = "DEPARTMENT_ID_FK")
        protected int departmentidfk;
        @XmlElement(name = "DESIGNATION_ID_FK")
        protected int designationidfk;
        @XmlElement(name = "LOCATION_ID_FK")
        protected String locationidfk;
        @XmlElement(name = "GRADE", required = true)
        protected String grade;
        @XmlElement(name = "OFFICE_MOBILE_NO")
        protected String officemobileno;

        /**
         * Gets the value of the nic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNIC() {
            return nic;
        }

        /**
         * Sets the value of the nic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNIC(String value) {
            this.nic = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTITLE() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTITLE(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the initials property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINITIALS() {
            return initials;
        }

        /**
         * Sets the value of the initials property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINITIALS(String value) {
            this.initials = value;
        }

        /**
         * Gets the value of the lastname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLASTNAME() {
            return lastname;
        }

        /**
         * Sets the value of the lastname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLASTNAME(String value) {
            this.lastname = value;
        }

        /**
         * Gets the value of the firstname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFIRSTNAME() {
            return firstname;
        }

        /**
         * Sets the value of the firstname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFIRSTNAME(String value) {
            this.firstname = value;
        }

        /**
         * Gets the value of the dateofbirth property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDATEOFBIRTH() {
            return dateofbirth;
        }

        /**
         * Sets the value of the dateofbirth property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDATEOFBIRTH(XMLGregorianCalendar value) {
            this.dateofbirth = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGENDER() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGENDER(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the maritalstatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMARITALSTATUS() {
            return maritalstatus;
        }

        /**
         * Sets the value of the maritalstatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMARITALSTATUS(String value) {
            this.maritalstatus = value;
        }

        /**
         * Gets the value of the epfno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEPFNO() {
            return epfno;
        }

        /**
         * Sets the value of the epfno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEPFNO(String value) {
            this.epfno = value;
        }

        /**
         * Gets the value of the departmentidfk property.
         * 
         */
        public int getDEPARTMENTIDFK() {
            return departmentidfk;
        }

        /**
         * Sets the value of the departmentidfk property.
         * 
         */
        public void setDEPARTMENTIDFK(int value) {
            this.departmentidfk = value;
        }

        /**
         * Gets the value of the designationidfk property.
         * 
         */
        public int getDESIGNATIONIDFK() {
            return designationidfk;
        }

        /**
         * Sets the value of the designationidfk property.
         * 
         */
        public void setDESIGNATIONIDFK(int value) {
            this.designationidfk = value;
        }

        /**
         * Gets the value of the locationidfk property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLOCATIONIDFK() {
            return locationidfk;
        }

        /**
         * Sets the value of the locationidfk property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLOCATIONIDFK(String value) {
            this.locationidfk = value;
        }

        /**
         * Gets the value of the grade property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGRADE() {
            return grade;
        }

        /**
         * Sets the value of the grade property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGRADE(String value) {
            this.grade = value;
        }

        /**
         * Gets the value of the officemobileno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOFFICEMOBILENO() {
            return officemobileno;
        }

        /**
         * Sets the value of the officemobileno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOFFICEMOBILENO(String value) {
            this.officemobileno = value;
        }

    }

}
