//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 09:48:38 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cclk.lk/schemas/entity/common/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.avn.ccl.bean.serviceclient.basicprofile;
